name: Build and Deploy
on:
  push:
    branches:
      - main
env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  PORT: ${{ secrets.PORT }}
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Install and Test Backend
      #   working-directory: ./backend
      #   run: |
      #     npm install
      #     export MONGODB_URI=$MONGODB_URI
      #     npm run test
      - name: Install and Test Customer Frontend
        working-directory: ./frontend/customer
        run: |
          npm install
          npm run test
      - name: Build Customer Frontend Docker Image
        working-directory: ./frontend/customer
        run: |
          docker build -t kuriguchi/stsweng-g5:customer_frontend-${{github.run_number}}
      # - name: Build Customer Server Docker Image
      #   working-directory: ./backend
      #   run: |
      #     docker build -t kuriguchi/stsweng-g5:backend-${{github.run_number}}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker Images to Docker Hub
        run: |
          docker push kuriguchi/stsweng-g5:customer_frontend-${{github.run_number}}
          # docker push kuriguchi/stsweng-g5:backend-${{github.run_number}}
        

  
