name: Build and Deploy
on:
  push:
    branches:
      - main
env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  PORT: ${{ secrets.PORT }}
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # - name: Install and Test Backend
      #   working-directory: ./backend
      #   run: |
      #     npm install
      #     export MONGODB_URI=$MONGODB_URI
      #     npm run test
      - name: Install and Test Customer Frontend
        working-directory: ./frontend/customer
        run: |
          npm install
          npm run test
        

  
